# Generated by Django 3.2.6 on 2021-08-31 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Garment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('collection', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('sizes', models.CharField(choices=[('XS', 'xs'), ('S', 's'), ('M', 'm'), ('L', 'l'), ('XL', 'xl')], default='S', max_length=2)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garments', to='ecom.category')),
            ],
        ),
    ]
