# Generated by Django 3.2.7 on 2021-09-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='photo_url',
            field=models.TextField(default='image unavaliable'),
        ),
    ]
