# Generated by Django 3.2.7 on 2021-09-06 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_listing_photo_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'get_latest_by': 'created_at'},
        ),
    ]
