# Generated by Django 3.2.6 on 2021-09-01 03:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_auto_20210831_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='days_on_market',
        ),
        migrations.AddField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
