# Generated by Django 3.2.7 on 2021-09-09 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='sizes',
            field=models.CharField(max_length=20),
        ),
    ]
