# Generated by Django 3.2.7 on 2021-09-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_listing_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='soldBy',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
