export const GET_LISTINGS = "GET_LISTINGS"
export const LISTING_DETAIL = "LISTING_DETAIL"
export const ADD_LISTING = "ADD_LISTING"
export const DELETE_LISTING = "DELETE_LISTING"
export const EDIT_LISTING = "EDIT_LISTING"

export const GET_ERRORS = "GET_ERRORS"

export const USER_LOADING = "USER_LOADING"
export const USER_LOADED = "USER_LOADED"
export const AUTH_ERROR = "AUTH_ERROR"

export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"

export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"

export const CREATE_MESSAGE = "CREATE_MESSAGE"
export const GET_MESSAGES = "GET_MESSAGES"

export const GET_SEARCHED = "GET_SEARCHED"